workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      flutter: stable
      xcode: latest
    cache:
      cache_paths:
        - ~/.gradle/caches
    scripts:
      - name: Install dependencies
        script: flutter pub get
      - name: Build app bundle
        script: flutter build appbundle --release
      - name: Build universal APK
        script: android-app-bundle build-universal-apk --bundle /Users/builder/clone/build/app/outputs/bundle/release/app-release.aab
      - name: Build iOS
        script: flutter build ios --release --no-codesign
      - name: Make ipa
        script: |
          mkdir -p build/ios/ipa/Payload
          cp -r build/ios/iphoneos/Runner.app build/ios/ipa/Payload/Runner.app
          7z a -tzip build/ios/ipa/Payload.zip build/ios/ipa/Payload
          mv build/ios/ipa/Payload.zip build/ios/ipa/app-release.zip
          mkdir build/ios/ipa/ipaFile
          cp build/ios/ipa/app-release.zip build/ios/ipa/ipaFile/app-release.zip
          echo "ipa created"
    artifacts:
      - build/app/outputs/bundle/release/app-release.aab
      - build/app/outputs/bundle/release/app-release-universal.apk
      - build/ios/iphoneos/Runner.app
      - build/ios/ipa/ipaFile/app-release.zip
