name: Flutter Build

on:
  workflow_dispatch:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-ios-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Doctor
        run: flutter doctor

      - name: Archive iOS app
        run: |
          flutter build ios --release --no-codesign

      - name: Make ipa file
        run: |
          ls build/ios/iphoneos/
          mkdir Payload
          cp -r build/ios/iphoneos/Runner.app Payload/Runner.app
          zip -r flutter_application_2.ipa Payload

      - name: Upload ios-build
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: flutter_application_2.ipa

      - name: Build macOS
        run: |
          flutter build macos --release

      - name: Upload macOS-build
        uses: actions/upload-artifact@v4
        with:
          name: macOS-build
          path: |
            build/macos/Build/Products/Release/flutter_application_2.app

  build-android-web-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies (Ninja, CMake, GTK)
        run: |
          sudo apt update
          sudo apt install -y ninja-build cmake libgtk-3-dev

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Doctor
        run: |
          flutter doctor

      - name: Build APK
        run: |
          flutter build apk --release

      - name: Upload apk-build
        uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: |
            build/app/outputs/flutter-apk/app-release.apk

      - name: Build web
        run: |
          flutter build web --release

      - name: Upload web-build
        uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: |
            build/web/

      - name: Build linux
        run: |
          flutter build linux --release

      - name: Upload linux-build
        uses: actions/upload-artifact@v4
        with:
          name: linux-build
          path: |
            build/linux/x64/release/bundle/

  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Doctor
        run: flutter doctor

      - name: Build Windows
        run: flutter build windows --release

      - name: Upload windows-build
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: |
            build\windows\x64\runner\Release\

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Install dependencies
        run: flutter pub get

      - name: Doctor
        run: flutter doctor

      - name: Build web
        run: |
          flutter build web --release --base-href /flutter_application_2/

      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          # Upload entire repository
          path: "./build/web"
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
